name: Frontend Build and hosting in aws using Cloudfront and S3

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Dist File and Increase package.json and Copy to S3 and invalidate cloudfront
    runs-on: self-hosted
    steps:
      - name: Github Checkout
        uses: actions/checkout@v2
      - name: Node version setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies and build
        run: |
          yarn   
          yarn run build

      - name: Push dist to S3 bucket
        run: |
          aws s3 cp ./dist/ s3://sulavfrontend --recursive
      - name: Invalidate Cloudfront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"