name: Frontend Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          yarn
          yarn install
          yarn build

      - name: Push dist's files to S3 bucket
        run: |
          aws s3 cp ./dist/ s3://sulavfrontend/ --recursive

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
